development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['HELPEXCHANGE_REDIS_URL'] %>:<%= ENV['HELPEXCHANGE_REDIS_PORT'] %>/<%= ENV['HELPEXCHANGE_REDIS_DB'] %>
  channel_prefix: helpexchange_server_production
